export const item: string
export const checked: string
export const text: string
export const btn__del: string
export const checkmark: string
export const light: string
export const del__light: string
export const circle: string
export const box: string
export const task: string
export const image: string
export const box__completed: string